### ISSUE TITLE
Mainnet asset launch suggestion: CryptoFighters

### ISSUE THREAD

**Issue by protinam** [ProjectWyvern/wyvern-schemas#14]
Name: CryptoFighters
Kind: ERC721 NFT
Smart Contract(s):
Website: https://cryptofighters.io/

**Comment by joesixpack** [comment]
Was this implemented?  I closed my own as a dupe, but it contained the smart contract address,

**Comment by protinam** [comment]
Yes; https://exchange.projectwyvern.com/assets?schema=CryptoFighters.

Thanks for finding the smart contract address, though, requirements were unclear. 5 WYV reward paid - https://etherscan.io/tx/0x340f572b3e1579fd25e80cf00cb6244cc18c111eb166b1ed64c3adfa12d9fc40 (but don't submit duplicates for any other issues I made without addresses yet)
