### ISSUE TITLE
Mainnet launch asset suggestion (example): CryptoKitties

### ISSUE THREAD

**Issue by protinam** [ProjectWyvern/wyvern-schemas#2]
**Name** CryptoKitties
**Kind** ERC721 nonfungible token
**Smart Contract(s)** https://etherscan.io/address/0x06012c8cf97bead5deae237070f9587f8e7a266d
**Website** https://www.cryptokitties.co/

My Ethereum address: 0x0084a81668b9a978416abeb88bc1572816cc7cac

**Comment by scott-lew-is** [comment]
Name CryptoPunks
Kind: nonfungible token
Smart Contract(s) 0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB
Website https://www.larvalabs.com/cryptopunks

**Comment by scott-lew-is** [comment]
done, sorry.

**Comment by protinam** [comment]
Closed by 782d8de7a70a28814e891d5c815da80a06e3ae82.
