### ISSUE TITLE
Mainnet launch asset suggestion: CryptoPunks

### ISSUE THREAD

**Issue by scott-lew-is** [ProjectWyvern/wyvern-schemas#3]
Name CryptoPunks
Kind: nonfungible token
Smart Contract(s) 0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB
Website https://www.larvalabs.com/cryptopunks

**Comment by protinam** [comment]
Thanks - can you include your Ethereum address in case we decide to accept this asset (and I expect we will)?
