### ISSUE TITLE
Mainnet asset suggestion: CryptoCelebrities

### ISSUE THREAD

**Issue by BobbyMcWho** [ProjectWyvern/wyvern-schemas#4]
**Name**: CryptoCelebrities
**Website**: https://cryptocelebrities.co/
**Type**: ERC721
**Smart Contract**:  https://etherscan.io/address/0xbb5Ed1EdeB5149AF3ab43ea9c7a6963b3C1374F7#code

My Ethereum Address: 0x3D9317cC2e741794C8b53E175e2C1e28170F6e18

**Comment by protinam** [comment]
This project has been shut down, I believe, although of course the tokens still exist on-chain.

@BobbyMcWho Do you know if there's still any user interest?

**Comment by BobbyMcWho** [comment]
I doubt the community wants to see it anywhere. Closing.
