### ISSUE TITLE
Competitors: Rare Bits & Open Sea

### ISSUE THREAD

**Issue by joesixpack** [ProjectWyvern/wyvern-schemas#41]
Rare Bits has over 500K, but mostly CryptoKitties.  Worth keeping an eye on.

Open Sea also, that pivoted from some other project.

**Comment by protinam** [comment]
Wyvern is a protocol, whereas both OpenSea and Rarebits (as far as I know) are applications - either could use Wyvern if they like. I don't think either issue their own nonfungible assets, so we can't add them to the Wyvern Exchange.

If you're looking to propose a specific course of action for Wyvern, you probably want [this repository](https://github.com/ProjectWyvern/WDPs).
