### ISSUE TITLE
Mainnet asset: ChainMonsters

### ISSUE THREAD

**Issue by protinam** [ProjectWyvern/wyvern-schemas#42]
*Name* ChainMonsters
*Type* ERC721 NFT
*Website* https://chainmonsters.io/
*Smart Contract(s)* [0xf7f6c2836293a661be2690fbacae97f3f027e9c4](https://etherscan.io/address/0xf7f6c2836293a661be2690fbacae97f3f027e9c4)

**Comment by protinam** [comment]
Implemented - https://exchange.projectwyvern.com/assets?schema=ChainMonsters - awaiting dev reply for more metadata.

**Comment by CineTek** [comment]
![image](https://user-images.githubusercontent.com/3392549/37461883-43554204-2850-11e8-8e2f-8e428508ec60.png)

you can call core.getMonster to retrieve generation, stats, etc - the last two "stats" digits are the types which are mapped to a name
In the zip you can find all monster types and their descriptions

[data.zip](https://github.com/ProjectWyvern/wyvern-schemas/files/1815250/data.zip)
