### ISSUE TITLE
Mainnet asset suggestion (Hard): EtherCraft

### ISSUE THREAD

**Issue by BobbyMcWho** [ProjectWyvern/wyvern-schemas#5]
**Name**: EtherCraft
**Website**: http://ethercraft.io
**Type**: ERC20
**Smart Contract**:  (Many) Listed here: https://dappradar.com/app/17/ethercraft

My Ethereum Address: 0x3D9317cC2e741794C8b53E175e2C1e28170F6e18

**Comment by protinam** [comment]
How are Ethercraft assets represented? Are different asset types different ERC20 contracts? Can new contracts be created or is that list static?

**Comment by BobbyMcWho** [comment]
The current list of all items and their respective erc20 contracts are listed here: http://ethercrafting.com/0xproject.html

**Comment by BobbyMcWho** [comment]
@pepthedon in their discord is very helpful if you want to reach out at any point. https://discord.gg/Y3XZ78T

**Comment by protinam** [comment]
EtherCraft has been listed; some more UX flow will be implemented tomorrow since the Exchange had to use a different asset indexing strategy.

10 WYV paid in https://etherscan.io/tx/0x26ed38be66bba45c5f9b14d385f2a4c7b41b3012954e86839e7847fa49a93a17.
